---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
spec:
  addresses:
{{- range .Values.addresses }}
  - {{ . }}
{{- end}}