{{- if .Values.spec.ingressNginx.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress-nginx
  namespace: {{ .Values.spec.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: {{ .Values.spec.ingressNginx.namespace }}
    server: {{ .Values.spec.destination.server }}
  # Allow all cluster-scoped resources to be created
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  # namespaceResourceBlacklist:
  # - group: ''
  #   kind: ResourceQuota
  # - group: ''
  #   kind: LimitRange
  # - group: ''
  #   kind: NetworkPolicy
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.spec.ingressNginx.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Values.spec.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.ingressNginx.namespace }}
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    chart: ingress-nginx
    targetRevision: {{ .Values.spec.ingressNginx.version }}
  project: ingress-nginx
{{- end }}
