{{- if .Values.spec.metallb.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metallb
  namespace: {{ .Values.spec.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: {{ .Values.spec.metallb.namespace }}
    server: {{ .Values.spec.destination.server }}
  # Allow all cluster-scoped resources to be created
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  # namespaceResourceBlacklist:
  # - group: ''
  #   kind: ResourceQuota
  # - group: ''
  #   kind: LimitRange
  # - group: ''
  #   kind: NetworkPolicy
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.spec.metallb.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: {{ .Values.spec.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.metallb.namespace }}
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: 'https://metallb.github.io/metallb'
    chart: metallb
    targetRevision: {{ .Values.spec.metallb.version }}
  project: metallb
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: {{ .Values.spec.metallb.namespace }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: {{ .Values.spec.metallb.namespace }}
spec:
  addresses:
{{- range .Values.spec.metallb.addresses }}
  - {{ . }}
{{- end}}
{{- end}}
